### PR TITLE
Additional discretizers

### PR DESCRIPTION
**Pull request by MarvinBleier**
Added the possibility to discretize supervised and implemented a first example discretizer. The FUSINTER Discretization works with entropy.

### CODE REVIEW

**Comment by fkoehne** [comment]
Good job on the TDD approach.

**Review by TobiasGoerke — APPROVED** [review]
Extensive and passing tests - looks good to me. 
Well done!

**Comment by fkoehne** [comment]
Checks have failed due to outdated version on maven central.

**Comment by TobiasGoerke** [comment]
[1.0.2](https://mvnrepository.com/artifact/de.viadee.xai.anchor/algorithm/1.0.2) ist online - wir können mergen :)

**Pull request merged**
